# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dasalaza <dasalaza@student.42barcelona.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/22 16:22:56 by anamedin          #+#    #+#              #
#    Updated: 2025/05/30 14:42:52 by dasalaza         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# ===================== PROJECT CONFIG ===================== #
NAME        = cub3D
CC          = cc
RM          = rm -f

CFLAGS      = -Wall -Wextra -Werror #-D LINUX=1
DEBUGFLAGS  = -g -fsanitize=address

UNAME       := $(shell uname)

# ===================== CONFIG EXTRA ===================== #
MAKEFLAGS   += -j$(shell nproc)

DEPDIR      := .deps
#DEPFLAGS    = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.d
DEPFLAGS    = -MMD -MP -MF $(DEPDIR)/$*.d	# <--- Generate dependencies in .deps/

DEBUG   ?= 0
SANITIZE?= 0

ifeq ($(DEBUG), 1)
	CFLAGS += -g -DDEBUG
endif

ifeq ($(SANITIZE), 1)
	CFLAGS += -fsanitize=address -fsanitize=undefined
endif

# ===================== PATHS ===================== #
PATH_MLX    = mlx
PATH_DELAY  = delay
PATH_BASS   = bass

# ===================== SOURCES ===================== #
SRC_CORE = \
	parser/cub_file.c \
	parser/cub_map_parser.c \
	parser/cub_map_setter.c \
	parser/cub_parser.c \
	parser/cub_setter.c \
	pathfinder/cub_astar.c \
	pathfinder/cub_node.c \
	pathfinder/cub_node_helper.c \
	pathfinder/cub_path.c \
	pathfinder/cub_pathfinder.c \
	pathfinder/cub_star_cardinal.c \
	render/cub_bitmap.c \
	render/cub_blur.c \
	render/cub_floor.c \
	render/cub_hud.c \
	render/cub_minimap.c \
	render/cub_raycast.c \
	render/cub_raycast2.c \
	render/cub_raycast3.c \
	render/cub_texture.c \
	render/cub_xquartz_layer.c \
	sprites/cub_doors.c \
	sprites/cub_goomba.c \
	sprites/cub_sprite_list.c \
	sprites/cub_sprites.c \
	utils/cub_checker.c \
	utils/cub_cleaner.c \
	utils/cub_error.c \
	utils/cub_keybinds.c \
	utils/cub_line_reader.c \
	utils/cub_line_reader_helper.c \
	utils/cub_rot.c \
	utils/cub_setup.c \
	utils/cub_utils.c \
	utils/cub_utils2.c \
	utils/cub_utils3.c \
	utils/cub_utils4.c \
	utils/cub_utils5.c \
	utils/cub_vec.c \
	utils/cub_vec2.c \
	world/cub_cardinal.c \
	world/cub_collide.c \
	world/cub_map.c \
	world/cub_player.c \
	world/cub_portal.c \
	world/cub_portal2.c \
	world/cub_portal_list.c \
	main.c

SRC_BONUS = \
	bonus/cub_sound_bonus.c \
	bonus/cub_other_bonus.c

SRC_OPTIONAL = \
	other/cub_other.c \
	other/cub_sound.c

# ===================== OBJECTS ===================== #
OBJS_CORE     = ${SRC_CORE:.c=.o}
OBJS_BONUS    = ${SRC_BONUS:.c=.o}
OBJS_OPTIONAL = ${SRC_OPTIONAL:.c=.o}

# ===================== DEPENDENCIES (.d files) ===================== #
# Generate dependency files in .deps/ directory
DEPS_CORE     = $(SRC_CORE:.c=.d)
DEPS_BONUS    = $(SRC_BONUS:.c=.d)
DEPS_OPTIONAL = $(SRC_OPTIONAL:.c=.d)
DEPS          = $(DEPS_CORE) $(DEPS_BONUS) $(DEPS_OPTIONAL)

# ===================== FLAGS ===================== #
FLAGS_BASE = -I$(PATH_MLX) -L$(PATH_MLX) -lmlx -lm -lXext -lX11 \
			 -I$(PATH_DELAY) -L$(PATH_DELAY) -ldelay \
			 -Wl,-rpath=./$(PATH_BASS)/,-rpath=./$(PATH_MLX)/,-rpath=./$(PATH_DELAY)/

FLAGS_BONUS = -I$(PATH_BASS) -L$(PATH_BASS) -lbass \
			  -I$(PATH_DELAY) -L$(PATH_DELAY) -ldelay \
			  $(FLAGS_BASE)

# ===================== RULES ===================== #
all: $(NAME)

$(NAME): $(OBJS_CORE) $(OBJS_OPTIONAL)
	$(MAKE) -C $(PATH_MLX)
	$(MAKE) -C $(PATH_DELAY)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS_CORE) $(OBJS_OPTIONAL) $(FLAGS_BASE)

bonus: $(OBJS_CORE) $(OBJS_BONUS)
	$(MAKE) -C $(PATH_MLX)
	$(MAKE) -C $(PATH_DELAY)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS_CORE) $(OBJS_BONUS) $(FLAGS_BONUS)

#%.o: %.c Makefile
#	@mkdir -p $(dir $(DEPDIR)/$*)
#	$(CC) $(CFLAGS) $(DEPFLAGS) -I$(PATH_MLX) -I$(PATH_BASS) -c $< -o $@ -D LINUX=true

# ===================== COMPILATION WITH DEPENDENCIES ===================== #
# <--- NEW: rule adapted to generate .d in $(DEPDIR)
#%.o: %.c Makefile
#	@mkdir -p $(dir $@) $(dir $(DEPDIR)/$*)
#	$(CC) $(CFLAGS) -MMD -MP -MF $(DEPDIR)/$*.d -I$(PATH_MLX) -I$(PATH_BASS) -c $< -o $@ -D LINUX=true

# COMPILACIÓN DE .o CON DEPENDENCIAS
#%.o: %.c Makefile
#	@mkdir -p $(dir $@)                     # crea el directorio del .o
#	@mkdir -p $(DEPDIR)/$(dir $<)          # crea el directorio correspondiente en .deps/
#	$(CC) $(CFLAGS) $(DEPFLAGS) -I$(PATH_MLX) -I$(PATH_BASS) -c $< -o $@ -D LINUX=true
#

%.o: %.c Makefile
	@mkdir -p $(dir $@)
	@mkdir -p $(DEPDIR)/$(dir $<)
	$(CC) $(CFLAGS) $(DEPFLAGS) \
		-I$(PATH_MLX) -I$(PATH_BASS) -Iinclude -Iparser -Ipathfinder -Irender -Iutils -Iworld -Iother -c $< -o $@ -D LINUX=true

clean:
	$(MAKE) -C $(PATH_MLX) clean
	$(MAKE) -C $(PATH_DELAY) clean
	$(RM) $(OBJS_CORE) $(OBJS_BONUS) $(OBJS_OPTIONAL)
	$(RM) -r $(DEPDIR)

fclean: clean
	$(MAKE) -C $(PATH_DELAY) fclean
	$(RM) $(NAME)

re: fclean all

norm:
	@echo "🔍 Norminette: $(SRC_CORE) $(SRC_BONUS) $(SRC_OPTIONAL)"
	@norminette $(SRC_CORE) $(SRC_BONUS) $(SRC_OPTIONAL)

# ===================== INCLUDE DEPENDENCIES ===================== #
# Include all dependency files from .deps/ directory
-include $(DEPS)

.PHONY: all clean fclean re bonus norm
